### ISSUE TITLE
[BUILD] Fail to install fVDB into ubuntu 22.04 with anaconda environment

### ISSUE THREAD

**Issue by stratonlive** [AcademySoftwareFoundation/openvdb#1949]
### Environment
**Operating System:** Ubuntu 22.04
**Version / Commit SHA:** feature/fVDB
**CMake Version:** 3.22.1
**Compiler:** gcc 11.4.0

### Describe the problem
When I try to run python setup.py develop or pip install . to install fvdb it always return error in cpp_extension.py which is used in setup.py line 299 

### To Reproduce
1. Checkout repo https://github.com/AcademySoftwareFoundation/openvdb/blob/feature/fvdb/fvdb/README.md#setting-up-a-conda-environment
2. See error

Traceback (most recent call last):
  File "/home/ubuntu/Downloads/openvdb-feature-fvdb/fvdb/setup.py", line 299, in <module>
    lib_ext = cpp_extension.CUDAExtension(
  File "/opt/conda/envs/fvdb_learn/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1076, in CUDAExtension
    library_dirs += library_paths(cuda=True)
  File "/opt/conda/envs/fvdb_learn/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1207, in library_paths
    if (not os.path.exists(_join_cuda_home(lib_dir)) and
  File "/opt/conda/envs/fvdb_learn/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 2416, in _join_cuda_home
    raise OSError('CUDA_HOME environment variable is not set. '
OSError: CUDA_HOME environment variable is not set. Please set it to your CUDA install root.

3. However I already make CUDA_HOME environment into /usr/local/cuda-12.1 as shown in Screen shot.

### Additional context
Screen shot of error is below

![fvdb build error](https://github.com/user-attachments/assets/d9ab10fe-5c11-44dc-8625-09ad4382038b)

**Comment by swahtz** [comment]
Hi @stratonlive 

Apologies, we forgot that we removed the build packages from the learn environment.  Right now the `fvdb_learn` environment just has the runtime packages needed to run the examples and notebooks once fVDB is built.

I've updated the README to recommend using the `dev_environment.yml` for building and dev work.  If you could go ahead and use this command to make your environment, this should solve your issue:

`conda env create -f env/dev_environment.yml`
