### ISSUE TITLE
Undefined symbol in pyopenvdb

### ISSUE THREAD

**Issue by dracwyrm** [AcademySoftwareFoundation/openvdb#258]
Hi,

I really hope you can help me track this error down, which is the same one for both v4.0.2 and v5.1.0.
The error:
```
openvdb-5.1.0/openvdb/python/test $ python TestOpenVDB.py 
Traceback (most recent call last):
  File "TestOpenVDB.py", line 39, in <module>
    import studioenv
ImportError: No module named 'studioenv'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "TestOpenVDB.py", line 44, in <module>
    import pyopenvdb as openvdb
ImportError: /usr/lib64/python3.5/site-packages/pyopenvdb.so: undefined symbol: _ZTIN5boost6python15instance_holderE
```
I'm using python 3.5. For v4.0.2, I'm using this patch https://github.com/dracwyrm/gentoo-ebuilds/blob/master/media-gfx/openvdb/files/openvdb-4.0.2-boost-1.65-numpy-support.patch which I took directly from the developer branch.  I don't know if other patches are needed, but since this same error occurs on v5.1.0, something else is happening here for me.

This is the ebuild I'm using at the moment: https://github.com/dracwyrm/gentoo-ebuilds/blob/master/media-gfx/openvdb/openvdb-4.0.2-r2.ebuild

Also, I use Pkg-Config to find IlmBase and OpenEXR, however the same thing happens when I use the default way of doing it in the source files.

What can I do to trace this more?

Thanks,
Jon

**Comment by dracwyrm** [comment]
Hi,
Thanks for replying. I ran the tests as you mentioned. This is with output from OpenVDB v5.1.0, but v4.0.2 has the same errors.

For some reason boost isn't linked in even though CMake configure finds it:
```
# ldd /usr/lib64/python3.5/site-packages/pyopenvdb.so
        linux-vdso.so.1 (0x00007ffd8a5c3000)
        libopenvdb.so.5.1 => /usr/lib64/libopenvdb.so.5.1 (0x00007f912315f000)
        libpython3.5m.so.1.0 => /usr/lib64/libpython3.5m.so.1.0 (0x00007f9122c95000)
        libHalf.so.23 => /usr/lib64/libHalf.so.23 (0x00007f9122a52000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f9122832000)
        libtbb.so.2 => /usr/lib64/libtbb.so.2 (0x00007f9122604000)
        libstdc++.so.6 => /usr/lib/gcc/x86_64-pc-linux-gnu/7.3.0/libstdc++.so.6 (0x00007f91221ff000)
        libm.so.6 => /lib64/libm.so.6 (0x00007f9121e76000)
        libgcc_s.so.1 => /usr/lib/gcc/x86_64-pc-linux-gnu/7.3.0/libgcc_s.so.1 (0x00007f9121c5f000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f9121897000)
        libboost_iostreams.so.1.65.0 => /usr/lib64/libboost_iostreams.so.1.65.0 (0x00007f9121679000)
        libz.so.1 => /lib64/libz.so.1 (0x00007f9121462000)
        libblosc.so.1 => /usr/lib64/libblosc.so.1 (0x00007f9121255000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007f9121051000)
        libutil.so.1 => /lib64/libutil.so.1 (0x00007f9120e4e000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f9123e76000)
        librt.so.1 => /lib64/librt.so.1 (0x00007f9120c46000)
        libbz2.so.1 => /lib64/libbz2.so.1 (0x00007f9120a35000)
        liblzma.so.5 => /lib64/liblzma.so.5 (0x00007f912080f000)
        liblz4.so.1 => /usr/lib64/liblz4.so.1 (0x00007f91205f2000)
        libsnappy.so.1 => /usr/lib64/libsnappy.so.1 (0x00007f91203ea000)
```
Relevant portion of configure:
```
-- Boost version: 1.65.0
-- Found the following Boost libraries:
--   iostreams
--   system
--   thread
--   regex
--   chrono
--   date_time
--   atomic
  
-- Found PythonInterp: /var/tmp/portage/media-gfx/openvdb-5.1.0/temp/python3.5/bin/python (found version "3.5.5") 
-- Found PythonLibs: /usr/lib64/libpython3.5m.so (found version "3.5.5") 
-- Boost version: 1.65.0
-- Found the following Boost libraries:
--   python3.5
```
On the system:
```
/usr/lib64/libboost_python-2.7-mt.so
/usr/lib64/libboost_python-2.7.so
/usr/lib64/libboost_python-2.7.so.1.65.0
/usr/lib64/libboost_python-3.5-mt.so
/usr/lib64/libboost_python-3.5.so
/usr/lib64/libboost_python-3.5.so.1.65.0
```
```
# nm /usr/lib64/libboost_python-3.5.so
nm: /usr/lib64/libboost_python-3.5.so: no symbols
```
Which is very odd.

Also, the person at this bug report has the exact same error and missing symbol https://bugs.gentoo.org/662822 Something is not getting linked somewhere. Other programs are able to link against libboost_python without issues. Gentoo uses --as-needed by default on everything, would this pose an issue for OpenVDB?

Many thanks for your help,
Jon

**Comment by OpenVDB-DevTeam** [comment]
> nm: /usr/lib64/libboost_python-3.5.so: no symbols

Is it a text file perhaps?  Maybe it's a linker script.

And just to confirm,

    objdump -p /usr/lib64/python3.5/site-packages/pyopenvdb.so | grep boost_python

produces no output, right?

> Gentoo uses --as-needed by default on everything, would this pose an issue for OpenVDB?

pyopenvdb depends directly on libboost_python, so `--as-needed` shouldn't be a problem.

**Comment by dracwyrm** [comment]
>> nm: /usr/lib64/libboost_python-3.5.so: no symbols
>
>Is it a text file perhaps? Maybe it's a linker script.
It's definitely a binary.

>>objdump -p /usr/lib64/python3.5/site-packages/pyopenvdb.so | grep boost_python
>
>produces no output, right?
Correct. Even though it's installed on the system, for some reason it's not being linked to. However, as shown earlier, it found python 3.5 boost libraries.

This is the full output.
```
$ objdump -p /usr/lib64/python3.5/site-packages/pyopenvdb.so

/usr/lib64/python3.5/site-packages/pyopenvdb.so:     file format elf64-x86-64

Program Header:
    LOAD off    0x0000000000000000 vaddr 0x0000000000000000 paddr 0x0000000000000000 align 2**21
         filesz 0x00000000005b23c0 memsz 0x00000000005b23c0 flags r-x
    LOAD off    0x00000000005b2d00 vaddr 0x00000000007b2d00 paddr 0x00000000007b2d00 align 2**21
         filesz 0x00000000000276d8 memsz 0x0000000000029800 flags rw-
 DYNAMIC off    0x00000000005c1d80 vaddr 0x00000000007c1d80 paddr 0x00000000007c1d80 align 2**3
         filesz 0x0000000000000260 memsz 0x0000000000000260 flags rw-
EH_FRAME off    0x000000000055a864 vaddr 0x000000000055a864 paddr 0x000000000055a864 align 2**2
         filesz 0x000000000000b02c memsz 0x000000000000b02c flags r--
   STACK off    0x0000000000000000 vaddr 0x0000000000000000 paddr 0x0000000000000000 align 2**4
         filesz 0x0000000000000000 memsz 0x0000000000000000 flags rw-
   RELRO off    0x00000000005b2d00 vaddr 0x00000000007b2d00 paddr 0x00000000007b2d00 align 2**0
         filesz 0x0000000000017300 memsz 0x0000000000017300 flags r--

Dynamic Section:
  NEEDED               libopenvdb.so.5.1
  NEEDED               libpython3.5m.so.1.0
  NEEDED               libHalf.so.23
  NEEDED               libpthread.so.0
  NEEDED               libtbb.so.2
  NEEDED               libstdc++.so.6
  NEEDED               libm.so.6
  NEEDED               libgcc_s.so.1
  NEEDED               libc.so.6
  SONAME               pyopenvdb.so
  INIT                 0x000000000037b7b8
  FINI                 0x00000000005190f4
  INIT_ARRAY           0x00000000007b2d00
  INIT_ARRAYSZ         0x0000000000000038
  FINI_ARRAY           0x00000000007b2d38
  FINI_ARRAYSZ         0x0000000000000008
  GNU_HASH             0x0000000000000190
  STRTAB               0x000000000004d030
  SYMTAB               0x000000000000f158
  STRSZ                0x00000000002d9db1
  SYMENT               0x0000000000000018
  PLTGOT               0x00000000007ca000
  PLTRELSZ             0x0000000000006a20
  PLTREL               0x0000000000000007
  JMPREL               0x0000000000374d98
  RELA                 0x000000000032c198
  RELASZ               0x0000000000048c00
  RELAENT              0x0000000000000018
  VERNEED              0x000000000032c078
  VERNEEDNUM           0x0000000000000005
  VERSYM               0x0000000000326de2
  RELACOUNT            0x0000000000000124

Version References:
  required from libgcc_s.so.1:
    0x0b792650 0x00 14 GCC_3.0
  required from libpthread.so.0:
    0x09691a75 0x00 08 GLIBC_2.2.5
  required from libm.so.6:
    0x09691a75 0x00 06 GLIBC_2.2.5
  required from libc.so.6:
    0x0d696914 0x00 11 GLIBC_2.4
    0x06969194 0x00 09 GLIBC_2.14
    0x09691a75 0x00 05 GLIBC_2.2.5
  required from libstdc++.so.6:
    0x0297f870 0x00 13 GLIBCXX_3.4.20
    0x0297f861 0x00 12 GLIBCXX_3.4.11
    0x0bafd179 0x00 10 CXXABI_1.3.9
    0x02297f89 0x00 07 GLIBCXX_3.4.9
    0x0297f871 0x00 04 GLIBCXX_3.4.21
    0x056bafd3 0x00 03 CXXABI_1.3
    0x08922974 0x00 02 GLIBCXX_3.4
```

**Comment by dracwyrm** [comment]
Apparently nm is not a good tool, as doing `readelf -s /usr/lib64/libboost_python-3.5.so.1.65.0` lists all the symbols, however, the needed one is absent. :(

**Comment by wuerzig** [comment]
Thanks a ton. Same problem, took me ages to find this thread. Ubuntu 18.04

**Comment by Anyeos** [comment]
Same problem in current end of 2019 trying to load a python library for Blender 2.82. 

Just to watch out: "readelf" will truncate the output if the command: "readelf -s [...] | grep [bla..bla..]" have "[bla...bla]" text too long. And you will give no results output. So you need to use the -W (wide) switch: 

`readelf -s -W /usr/lib/x86_64-linux-gnu/libboost_python3-py37.so | grep _ZTIN5boost6python15instance_holderE`

**Comment by robelmilk** [comment]
Can someone please specify what I have to exactly do to install pyopenvdb on Debian 10

**Comment by malaterre** [comment]
@robelmilk Simply do:

`# apt install python3-openvdb`

**Comment by Idclip** [comment]
As this issue is pretty old and seems resolved(?) I'll be closing this. Please create a new issue if you're running into problems!
